[RFR-182] Add file counts to meta data
cyface-de/uploader pull request #4
Opened 2023-10-26 12:41 UTC by hb0

2023-10-31 12:11 UTC, hb0 reviewed
pre-reviewed

2023-10-31 12:11 UTC, hb0 commented on build.gradle.kts
> +extra["cyfaceSerializationVersion"] = "3.2.0-alpha2"
FIXME

2023-10-31 12:11 UTC, hb0 commented on src/main/kotlin/de/cyface/uploader/Authenticator.kt
The new authentication is still in the android-backen library for now, but we can remove this old authentication already.
We'll port the new authentication to this library if possible in the future.

2023-10-31 12:11 UTC, hb0 commented on src/main/kotlin/de/cyface/uploader/DefaultUploader.kt
> +            FileInputStream(file).use { fis ->
ensures the stream is closed

2023-10-31 12:11 UTC, hb0 commented on src/main/kotlin/de/cyface/uploader/DefaultUploader.kt
To hide the whitespace changes, change the settings here in Github PR review page.

2023-10-31 12:11 UTC, hb0 commented on src/main/kotlin/de/cyface/uploader/DefaultUploader.kt
>      }
This might change slightly but the Collector Part will be done separately in the future.

2023-10-31 12:11 UTC, hb0 commented on src/main/kotlin/de/cyface/uploader/DefaultUploader.kt
> +        }
just moved hede from the removed DefaultAuthenticatior.

2023-11-01 10:53 UTC, muthenberg requested changes
See my comments inline

2023-11-01 10:53 UTC, muthenberg commented on src/main/kotlin/de/cyface/uploader/DefaultUploader.kt
> +                attributes["startLocLat"] = metaData.startLocation!!.latitude.toString()
Does this not compile without the `!!`? Usually Kotlin should know that `!!` is not necessary after a check for `null`. Why was this not there previously?

2023-11-01 10:53 UTC, muthenberg commented on src/main/kotlin/de/cyface/uploader/RequestInitializeHandler.kt
> +            headers["startLocLat"] = metaData.startLocation!!.latitude.toString()
Same as above.

2023-11-01 10:53 UTC, muthenberg commented on src/main/kotlin/de/cyface/uploader/DefaultUploader.kt
I see not whitespace changes.

2023-11-01 10:53 UTC, muthenberg commented on src/main/kotlin/de/cyface/uploader/DefaultUploader.kt
> +        endpoint: URL,
Why do you specify endpoint here, in addition to the apiEndpoint property of the class?

2023-11-02 08:36 UTC, hb0 reviewed
See my replies / commits

2023-11-13 12:45 UTC, muthenberg requested changes
See my comment.

2023-11-13 12:45 UTC, muthenberg commented on src/main/kotlin/de/cyface/uploader/DefaultUploader.kt
> +    override fun filesEndpoint(measurementId: Long): URL {
This should read attachmentsEndpoint

2023-11-13 13:26 UTC, merged